spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/cards/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/accounts/**
        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path=/users/**
        - id: r4
          uri: http://localhost:8084/
          predicates:
           - Path=/transactions/**
        - id: r5
          uri: http://localhost:8085/
          predicates:
            - Path=/eer/**
        - id: r6
          uri: http://localhost:8085/
          predicates:
            - Path=/piece-jointe/**


